//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBasedSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Note()
        {
            this.Specialists = new HashSet<Specialist>();
        }
    
        public int NoteId { get; set; }
        public string NotesDescription { get; set; }
        public Nullable<bool> TakingNewPatients { get; set; }
        public string price { get; set; }
        public string Waiting_Time { get; set; }
        public Nullable<int> SpecialistId { get; set; }
        public Nullable<bool> IsBooking { get; set; }
    
        public virtual Note Notes1 { get; set; }
        public virtual Note Note1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Specialist> Specialists { get; set; }
    }
}
