//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBasedSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialist
    {
        public int SpecialistId { get; set; }
        public string Title { get; set; }
        public string SpecialistName { get; set; }
        public string MobileNo { get; set; }
        public string PhoneNo { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string EmailAddress { get; set; }
        public string BusinessName { get; set; }
        public Nullable<int> SpecialistTypeId { get; set; }
        public string Surname { get; set; }
        public string OfficeNo { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string SubMenu { get; set; }
        public Nullable<int> Age { get; set; }
        public string PostCode { get; set; }
        public string Suburbs { get; set; }
        public string State { get; set; }
        public Nullable<int> NoteId { get; set; }
    
        public virtual Note Note { get; set; }
    }
}
